version: "3.0"
services:
  vault-enterprise:
    image: hashicorp/vault-enterprise:latest
    environment:
      VAULT_LICENSE: ${VAULT_LICENSE_CI}
    ports:
      - 8200:8200
    privileged: true
    cap_add:
      - IPC_LOCK
    command: vault server -config=/vault/config/vault.hcl
    volumes:
      - ./vault-server.hcl:/vault/config/vault-server.hcl
      - vault-data:/vault/data
