version: "3.0"
services:
  vault-enterprise:
    image: hashicorp/vault-enterprise:latest
    environment:
      VAULT_LICENSE_PATH: /vault/config/vault.hclic 
    ports:
      - 8200:8200
    privileged: true
    cap_add:
      - IPC_LOCK
    command: vault server -config=/vault/config/vault-server.hcl
    volumes:
      - ./vault-server.hcl:/vault/config/vault-server.hcl
      - type: bind
        source: ./vault-data
        target: /vault/data
      - type: bind
        source: ./vault.hclic
        target: /vault/config/vault.hclic
